[package]
name = "tinkiva-docker-manager"
version = "0.14.0"
edition = "2024"
rust-version = "1.85"
description = "Panel de despliegue Docker ultraligero y de un solo nodo"
license = "MIT"
authors = ["Tinkiva"]

[[bin]]
name = "tmanager"
path = "src/main.rs"

[dependencies]
argon2 = { version = "0.5.3", default-features = false, features = ["alloc", "password-hash"] }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
